version: '3'

services:
  nodejs_household:
    entrypoint: "/bin/sh ./docker-entrypoint.sh"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/application
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - traefik.http.routers.household.rule=Host(`${DOMAIN}`)
      - "traefik.http.routers.household.tls.certresolver=lets_encrypt_resolver"
    expose:
      - 8111
    networks:
      proxy:
        ipv4_address: 10.200.0.61

networks:
  proxy:
    external: true
